version: '3'
services:
  allure:
    image: mrTarasFin/allure
    command: /bin/sh -c "./allure serve -p 80 /allure-results"
    ports:
      - "8800:80"
    volumes:
      - ${PWD}/allure-results:/allure-results

chrome:
    image: selenium/node-chrome:4.8.3-20230404
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443